### ISSUE TITLE
Error: Unable to resolve plugin Python 'SKOPOSSFTPDownload_v1.0\SKOPOSSFTPDownload_v1.0Engine.py'

### ISSUE THREAD

**Issue by marcopeters-exsell** [SKOPOS-ELEMENTS/SFTPTools_Alteryx#11]
**Describe the bug**
After the update of Alteryx to 2021.3.3.63061 (we came from a very old 2020 version), the skopos tool does not connect anymore. Initially it gave an error: 'You have found a bug'. After that, it gave the error Unable to resolve plugin Python 'SKOPOSSFTPDownload_v1.0\SKOPOSSFTPDownload_v1.0Engine.py'

**To Reproduce**
1. Create a new flow, add the SKOPOS tool, add credentials and try to run the flow. 
=

**Expected behavior**
Expected behavior is to download files to a blob or generate a list of contents on the SFTP.

**Screenshots**
![image](https://user-images.githubusercontent.com/74704280/139428879-df3cbfc4-72fc-47cc-b0b0-ec045dc575ef.png)

**Desktop (please complete the following information):**
 - Windows server
 - Alteryx designer x64 2021.3.3.63061 (we have a server license)
 - 2021.3.3.63061

**Comment by neurotroph** [comment]
Hi @marcopeters-exsell ,

have you re-installed the tool after upgrading Alteryx with the latest yxi installer?

Best
Christopher

**Comment by marcopeters-exsell** [comment]
> Hi @marcopeters-exsell ,
> 
> have you re-installed the tool after upgrading Alteryx with the latest yxi installer?
> 
> Best Christopher

We had the latest version installed. We have created or own python solution now.
