### ISSUE TITLE
Install package only installed the 'SFTP Downloader'. Missing the SFTP Uploader tool.

### ISSUE THREAD

**Issue by jalenbraegelmann** [SKOPOS-ELEMENTS/SFTPTools_Alteryx#12]
Trying to install the two tools on our Alteryx Server instance. 

Server Version: 2021.3.4.00445

Package running: SFTPTools_Alteryx-1.0.2-alpha

I downloaded the zip file, the navigated to the .yxi file under (SFTPTools_Alteryx-1.0.2-alpha\alteryx_installer)

The installer ran successfully in under 2 minutes, but failed to install the STFP Uploader tool.

How do I get the second tool installed?

**Comment by mi-ellers** [comment]
Hi, @jalenbraegelmann. 

Thank you for the question!

This was a bug in the installer. I included the Upload-Tool in the latest commit.

I hope this helps!

Kind regards

Michael

**Comment by jalenbraegelmann** [comment]
[PythonDependencyInstall.log](https://github.com/SKOPOS-ELEMENTS/SFTPTools_Alteryx/files/8049424/PythonDependencyInstall.log)
I'm able to see the folder of the install now after the latest commit and it says it installed successfully. But the Upload tool doesn't show up in Designer (the Downloader does, however). I've very green in this space is there anything else I can try?

Thanks!
