### ISSUE TITLE
Update Python Version

### ISSUE THREAD

**Issue by jsteans** [SKOPOS-ELEMENTS/SFTPTools_Alteryx#5]
Hi,
Will you be updating the python version used in the tool? Given Alteryx updated to version 3.8 of python, the tool no longer works as it is using version 3.6 of python.

![image](https://user-images.githubusercontent.com/77021562/103686513-edcaab80-4f5c-11eb-8ddd-524f038b775a.png)

**Comment by neurotroph** [comment]
Hi @jsteans ,

yes, we will be updating the tool to be working with Alteryx 2020.4 and later. However, the pysftp library we use does not work well with Python 3.8, so we need to refactor large parts of the tool. Might take a couple of weeks before we find the time to update the tool internally and release it afterwards. I will post in this issue as soon as we have an updated release.

Best
Christopher

**Comment by nadiahnoorlin** [comment]
I received an error with "Exit status 1: python setup.py egg_info Check the logs for full command output" during installation of  SFTP tool, how to solve this problem?
![error sftp](https://user-images.githubusercontent.com/47973127/110902235-7e987b80-8340-11eb-9b14-2cdf97ab66b3.png)

**Comment by neurotroph** [comment]
@nadiahnoorlin Do you use Alteryx 2020.4 or newer? Then, this might likely be the problem explained above: our tool version is currently incompatible with Python 3.8 - we are still working on it, but haven't deployed Alteryx 2020.4, so can't really test everything yet.

**Comment by litesign** [comment]
> yes, we will be updating the tool to be working with Alteryx 2020.4 and later. However, the pysftp library we use does not work well with Python 3.8, so we need to refactor large parts of the tool. Might take a couple of weeks before we find the time to update the tool internally and release it afterwards. I will post in this issue as soon as we have an updated release.

Christopher,
I know we are all busy, but was wondering if you had made any progress on the update yet?
Thanks,
Rod

**Comment by neurotroph** [comment]
Hi @litesign , we have not yet upgraded our server to Alteryx 2021.1 or later as the new versions broke many of our workflows, not only because of the SFTP tool. We have a version in testing, but it has problems with the SSL bindings when loaded in Alteryx. As soon as we are closer to upgrading our server (2021.1 has been released last week and we are currently evaluating), we should have a new version ready.

**Comment by neurotroph** [comment]
@litesign @nadiahnoorlin @jsteans Could you kindly try to install this pre-released yxi? https://github.com/SKOPOS-ELEMENTS/SFTPTools_Alteryx/releases/tag/v1.0.2-alpha

**Comment by litesign** [comment]
I have installed the new XYI on Alteryx Version: 2021.1.4.26400. The XYI
seems to have installed successfully. However I am getting the following
error message when I try to run with the same settings that are successful
with the old macro...

Error: SFTP Downloader (2): Traceback (most recent call last):
  File "main.py", line 5, in <module>
  File
"C:\ProgramData\Alteryx\Tools\SKOPOS_SFTP_venv\Lib\site-packages\pysftp\__init__.py",
line 12, in <module>
    import paramiko
  File
"C:\ProgramData\Alteryx\Tools\SKOPOS_SFTP_venv\Lib\site-packages\paramiko\__init__.py",
line 22, in <module>
    from paramiko.transport import SecurityOptions, Transport
  File
"C:\ProgramData\Alteryx\Tools\SKOPOS_SFTP_venv\Lib\site-packages\paramiko\transport.py",
line 89, in <module>
    from paramiko.dsskey import DSSKey
  File
"C:\ProgramData\Alteryx\Tools\SKOPOS_SFTP_venv\Lib\site-packages\paramiko\dsskey.py",
line 37, in <module>
    from paramiko.pkey import PKey
  File
"C:\ProgramData\Alteryx\Tools\SKOPOS_SFTP_venv\Lib\site-packages\paramiko\pkey.py",
line 31, in <module>
    import bcrypt
  File
"C:\ProgramData\Alteryx\Tools\SKOPOS_SFTP_venv\Lib\site-packages\bcrypt\__init__.py",
line 25, in <module>
    from . import _bcrypt  # type: ignore
ImportError: DLL load failed while importing _bcrypt: The specified module
could not be found.

One suggestion I'd like to make is that you somehow indicate the macro
version number in the Configuration screen of the macro. I still have the
older version installed (and am able to use it on a non-admin older version
of Alteryx, but on the new version, they both show up and there's no clear
way to differentiate between the two Downloader tools.

Thanks for working on this.
Please let me know if you need further testing.
Rod Light

**Comment by litesign** [comment]
Chris,
That's seems to have solved the issue. Thanks!
Rod

**Comment by litesign** [comment]
Chris,
A question on the installation...does the macro need to be installed on an
Admin version of Alteryx? I seem to be running into an issue when installed
using the Non-Admin version.
Thanks,
Rod

**Comment by neurotroph** [comment]
@litesign We haven't tried, but normally it should work for Non-Admin installations as well. We are not installing anything out of the ordinary that would require admin privileges. When setting the PATH variable system-wide for the SSL bindings, the installation directory (admin vs non-admin) should not matter. Can you elaborate on the issue you have (best to open a new issue for that)?

**Comment by litesign** [comment]
Actually I'm getting the same error as above. Sorry, but I needed to use
Support to provide the Admin access to change the environmental settings
and now I don't remember if I did them at the user level or system level.
Would that make a difference?

**Comment by litesign** [comment]
Chris,
So the install I have on my client's laptop is non-admin. It finally dawned
on me that the PATH directories you gave me would be for an Admin
installation. In an Admin installation, the bin directory is in the Program
Files folder, but for a non-Admin installation of Alteryx, the bin
directory is actually in C:\Users\username\AppData\Local\Alteryx\bin. So
I'm thinking that the PATH environmental settings you gave me are basically
pointing nowhere. Instead, I should put the PATH directories as something
like "%USERPROFILE%\AppData\Local\Alteryx\bin". Does that make sense?
Thanks,
Rod

**Comment by neurotroph** [comment]
Yes, that makes sense. If you have both versions installed at the same time, the C:\Program Files\... path will resolve fine for both versions. If, on the other hand, you only have the Non-Admin version installed, the path will go nowhere and you have to use the non admin directories in your path.

Thanks for your help and feedback. I will update the final yxi with installation instructions regarding the path in the next few days. Closing the issue for now - the pre-release version on GitHub should work.

Just as an aside: I will rewrite the tool using updated libraries and based on Alteryx' new platform SDK, so hopefully we can achieve a longer compatibility through that.

**Comment by litesign** [comment]
Thanks for the confirmation...and for letting me be a part of the process.
I really appreciate you sharing the tool!
Rod
