### ISSUE TITLE
Installing on Alteryx HUB

### ISSUE THREAD

**Issue by bkjedr** [SKOPOS-ELEMENTS/SFTPTools_Alteryx#6]
When installing with  the yxi-installer.exe on the Alteryx HUB we encounter some errors. Below is the command we have used on the server:

 .\yxi-installer.exe install-yxis --install-type "Admin" --uninstall-previous --alteryx-path "D:\HUB_DATA\" ".\ELEMENTS_SFTPTools.yxi"

And the error we got was the follwing:

yxi_installer - INFO - Alteryx path specified is D:\HUB_DATA\.
yxi_installer - INFO - YXI's to install are ('.\\ELEMENTS_SFTPTools.yxi',).
yxi_installer - INFO - Install mode: Admin.
yxi_installer - INFO - Uninstall previous: True.
yxi_installer.validation - DEBUG - Validating yxis...
yxi_installer.validation - DEBUG - ELEMENTS_SFTPTools.yxi valid.
yxi_installer.validation - DEBUG - Validating alteryx install location...
yxi_installer.validation - DEBUG - Valid alteryx install location given
yxi_installer - INFO - All input validation has passed.
yxi_installer - INFO - All YXI's will be installed to C:\ProgramData\Alteryx\Tools
yxi_installer - INFO - Copying tools to temporary directory
yxi_installer.utilities - INFO - Copying tools to C:\Users\u-bkje\AppData\Local\Temp\tmp5mpuzrcz
yxi_installer.python - INFO - ELEMENTS_SFTPTools.yxi uses a python tool family.
Traceback (most recent call last):
  File "yxi_installer\__main__.py", line 189, in <module>
  File "site-packages\click\core.py", line 764, in __call__
  File "site-packages\click\core.py", line 717, in main
  File "site-packages\click\core.py", line 1137, in invoke
  File "site-packages\click\core.py", line 956, in invoke
  File "site-packages\click\core.py", line 555, in invoke
  File "yxi_installer\__main__.py", line 96, in install_yxis
  File "yxi_installer\python.py", line 119, in _collect_environment_specifications
  File "yxi_installer\python.py", line 79, in _get_wheel_directory
IndexError: list index out of range
[8944] Failed to execute script __main__

We are using Alteryx HUB version Analytics Hub version 2020.2.45+737f219a

The tool is being used on several workflows on our Scheduler but we would like to move it to the HUB. 

Best Regards,

Bo Kjeldgaard

**Comment by neurotroph** [comment]
Hi @bkjedr , thanks for reporting this!

Unfortunately, we do not have an AAH available to us for testing yet. So, if anyone with an AAH could look into it, this help would be much appreciated.

As soon as we have an analytics hub available, we will check if our new version (see #5 ) works with the AAH as well.

Best
Christopher

**Comment by bkjedr** [comment]
Hi Christopher

Thank you for your reply.

Best Regards,

Bo

-- -  -   -    -     -      -       -        -

Bo Kjeldgaard
Medieforsker, DR Medieforskning

[DR]

DR
DR Byen
Emil Holms Kanal 20, opg. 3-4
DK-0999 København C
T +45 3520 3040
D +45 3520 4055
M +45 2854 4055
bkje@dr.dk
http://www.dr.dk

**Comment by neurotroph** [comment]
As the AAH is not continued by Alteryx, we will not specifically check for compatibility. The pre-release, however, might work as it should be compatible with 2021.1+ and thus also the AAH: https://github.com/SKOPOS-ELEMENTS/SFTPTools_Alteryx/releases/tag/v1.0.2-alpha
